### PR TITLE
Replace obsolete define-suffix-command with transient-define-suffix

### LINKED ISSUE #7: define-suffix-command is now transient-define-suffix
`define-suffix-command` has been obsolete for a while.

It now causes the following to not be defined:
* `magit-lfs-fetch-from-pushremote`
* `magit-lfs-fetch-from-upstream`
* `magit-lfs-pull-from-pushremote`
* `magit-lfs-pull-from-upstream`
* `magit-lfs-push-current-to-pushremote`
* `magit-lfs-push-current-to-upstream`

It should be replaced with `transient-define-suffix`.

### PR DESCRIPTION
**Pull request by MunsterPlop**
* closes #7

### CODE REVIEW

**Comment by jimmy-wong-beamery** [comment]
This seems to be fixed on master ages ago already, this seems to be a Melpa issue. 

https://github.com/Ailrun/magit-lfs/blob/master/magit-lfs.el#L96

**Comment by wyuenho** [comment]
This seems to be fixed on master ages ago already, this seems to be a Melpa issue.

https://github.com/Ailrun/magit-lfs/blob/master/magit-lfs.el#L96

**Comment by wyuenho** [comment]
Ping @Ailrun . Transient has removed the `define-suffix-command`, this is urgent as magit-lfs is broken.

**Review by Ailrun — APPROVED** [review]
Thank you for the contribution!

**Pull request merged**
